git:
  submodules: false
before_install:
  - git submodule init
  - git submodule update
language: rust
rust:
  - stable
script:
  - cargo check
  - cargo run --bin coverage --release -- dir external/rust/src
  - cargo run --bin snapshots --release
