[package]
name = "rust-grammar"
version = "0.1.0"
authors = ["The Rust Project Developers"]

[dependencies]
gll = "0.0.2"
proc-macro2 = "0.4.0"
structopt = "0.2.12"
walkdir = "2.2.6"

[build-dependencies]
gll = "0.0.2"
walkdir = "2.2.6"
